### ISSUE TITLE
Selecting a monster and going back, immediately pushes the same monster detail again.

### ISSUE THREAD

**Issue by SpacyRicochet** [Thomvis/Construct#2]
![RPReplay_Final1601901626](https://user-images.githubusercontent.com/904596/95096196-4014ea00-072c-11eb-89ae-48acd0370f51.gif)

**Comment by Thomvis** [comment]
Thanks for reporting! I can’t reproduce this unfortunately. What branch/app version and OS version are you using?

**Comment by SpacyRicochet** [comment]
App Store version (latest, presumably); iOS 14.0

**Comment by Thomvis** [comment]
Thanks. This is one of the things that broke on iOS 14, I have yet to push an Xcode 12 build to the App Store. `main` is much better on iOS 14 but needs a few last refinements. You could try the latest TestFlight build if this issue is a deal breaker.

**Comment by Thomvis** [comment]
I believe this has been resolved with version 1.1, which was released yesterday. Feel free to reopen the issue if it persists.

**Comment by SpacyRicochet** [comment]
Yup, it's fixed!
