### ISSUE TITLE
"Cannot be type checked in reasonable time" compiler error while building for preview.

### ISSUE THREAD

**Issue by SpacyRicochet** [Thomvis/Construct#3]
The following doesn't happen during regular building, but only when trying to preview a SwiftUI build in the Canvas.

Mostly this is just annoying, but it probably can be broken up into tinier pieces to alleviate this. 

Xcode 12.2 beta 2
- master branch

```
/Users/brunoscheele/Projects/forks/Construct/Construct/Compendium/View/CompendiumItemDetailView.swift:29:16: The compiler is unable to type-check this expression in reasonable time; try breaking up the expression into distinct sub-expressions
```

<img width="1276" alt="Screen Shot 2020-10-10 at 20 19 30" src="https://user-images.githubusercontent.com/904596/95662284-1269df80-0b36-11eb-8e9e-46fc59dae691.png">

**Comment by Thomvis** [comment]
Previews broke very early on in Construct's development, or at least they became very unreliable so I gave up on them. I've heard similar stories from other developers. I expect many changes to be needed to make previews work and therefore it is not a goal for now.
